// 공개 포트폴리오 전시 데이터.
// 날짜가 명시되지 않은 프로젝트의 위치는 시간순을 뜻하지 않는다.
window.PORTFOLIO = {
  skillScale: 10,
  nodes: [
    {id:'qa',group:'work',kind:'official',date:'2022.01–2022.08',short:'홈페이지 QA',title:'항만 물류 인큐베이션 홈페이지 QA',x:10,y:49,summary:'버튼 스타일과 인터랙션 결과 피드백의 일관성을 점검하고, 이후 JSP 코드 수정까지 직접 맡았습니다.',problem:'버튼 스타일이 화면·권한별로 일관되지 않았고, 등록 같은 인터랙션을 완료해도 처리 결과를 알려주는 피드백이 부족했습니다. 권한이 다른 계정으로 같은 페이지를 볼 때도 버튼의 모양과 상태가 달라 혼란을 줄 수 있었습니다.',solution:'처음에는 문제 화면을 캡처해 상급자(대리)에게 메신저로 보고했습니다. 이후에는 직접 JSP 코드를 살펴 함수 연결 미스매치 등을 수정하고, 버튼 스타일과 동작 후 피드백 문제를 개선했습니다.',metrics:['점검 범위: 약 15~20개 페이지 (기억에 따른 추정)','발견 결함: 약 10건 (기억에 따른 추정)'],skill:null},
    {id:'potmis',group:'work',kind:'official',date:'2022.08–2023.08',short:'PORTMIS 운영',title:'PORTMIS 서비스 운영 및 유지관리',x:22,y:64,summary:'주간에는 플랫폼 전화상담과 예외 데이터 조회를, 야간에는 서비스 모니터링을 맡았습니다.',problem:'PORTMIS 사용이 익숙하지 않은 고객의 문의와, 통합 과정에서 미신고·누락되었거나 DB 기록을 찾기 어려운 선박처럼 화면에서 바로 해결할 수 없는 예외 케이스가 있었습니다. 새벽 3시경 일부 정보통신 통합 서비스가 중단됐을 때는 대응 절차를 몰라 헤맸던 경험도 있습니다.',solution:'주간에는 고객의 사이트 이용을 안내하고, 서비스 화면에서 제공하지 않는 정보를 DB 쿼리로 조회해 예외 케이스를 처리했습니다. 야간에는 PORTMIS 서비스를 모니터링했습니다. 새벽 장애 경험은 이후 인시던트 대응을 돕는 Sentinel을 구상한 계기가 됐습니다.',metrics:['주간 상담·조회: 평균 30~50건 (기억에 따른 추정)','야간: 서비스 모니터링','새벽 3시경 일부 서비스 장애 경험'],skill:{key:'sql',value:3,label:'RDB · SQL',level:'초급'}},
    {id:'sparta',group:'flutter',kind:'official',date:'2023',short:'스파르타 창 5기',title:'팀 스파르타 창 5기',x:23,y:28,summary:'개발 역량을 키우기 위해 참여했고, Flutter를 처음 접한 계기가 됐습니다.',problem:'당시 회사 업무에서는 개발 역량을 기를 기회가 적었습니다. 강의를 찾던 중 단순히 만드는 서비스가 아니라 고객이 실제로 돈을 내는 서비스를 만들어야 한다는 글을 접했습니다.',solution:'그 문제의식으로 팀 스파르타 창 5기에 참여했습니다. 창업 교육의 세부 내용보다는 크로스 플랫폼 기술 Flutter를 접한 경험이 이후 프로젝트로 이어졌습니다.',metrics:['수료: 2023','Flutter 자기평가: 2 / 10'],skill:{key:'flutter',value:2,label:'Flutter',level:'초급'}},
    {id:'datacenter',group:'work',kind:'official',date:'2024년 초–2025.09',short:'데이터센터 점검',title:'LG 데이터센터 서버 정기점검',x:38,y:53,summary:'월 1회 Linux 서버의 용량과 메모리 사용량을 점검했습니다.',problem:'서비스를 제공하는 서버와 음성 데이터를 저장하는 DB 서버가 한 장비로 운영되는 구성을 확인했습니다. 운영상 분리가 가능한지 의문이 생겼습니다.',solution:'배포 서버와 백업 서버의 용량·메모리 사용량을 정기 점검하고, 서버 구성에 대한 우려를 건의했습니다. 계약 규모상 불가피한 설계라는 답변을 받았으며, 별도 구조 변경은 진행하지 않았습니다.',metrics:['점검 주기: 월 1회','점검 규모: 5세트 × 배포·백업 서버 = 총 10대 (기억에 따른 추정)'],skill:{key:'linux',value:2,label:'Linux',level:'초급'}},
    {id:'daily',group:'flutter',kind:'personal',date:'2024년 초–2025년 초',short:'Daily School',title:'Daily School',x:39,y:17,summary:'현업 초등 교사가 리드한 8인 팀에서 첫 Flutter 팀 프로젝트를 진행하고 2025년 초 릴리즈했습니다.',problem:'첫 팀 Flutter 프로젝트에서 여러 기능을 일관된 상태·인증·API 통신 구조로 연결해야 했습니다.',solution:'6개 메뉴 중 홈·수업·생활·통계 4개를 구현하고, 회원가입·로그인·로그인 상태관리, JWT 세션 관리, Riverpod 상태관리, DIO 통신 전·후처리 구조를 담당했습니다. 이 과정에서 클린 아키텍처를 학습했습니다. Java(Spring) 백엔드와 Jenkins 배포 자동화는 백엔드 엔지니어가 담당했습니다.',metrics:['팀 규모: 8명','담당 메뉴: 6개 중 4개','릴리즈: 2025년 초','Flutter 자기평가: 4 / 10'],skill:{key:'flutter',value:4,label:'Flutter',level:'중급'},link:'https://devwww.dailyschool.co.kr/'},
    {id:'winforms',group:'work',kind:'official',date:'2024년 말경–2025.09',short:'업무 프로그램 개선',title:'항만물류 퇴직자 관리 프로그램 개선',x:51,y:68,summary:'요구사항 분석부터 C# WinForms 프로그램 오류 개선까지 직접 맡았습니다.',problem:'정렬 오류, 쿼리 결과 불일치, 넓은 조회 범위에 따른 타임아웃·프로그램 종료, 버튼 클릭 시 종료되는 오류가 있었습니다.',solution:'SQL 관련 문제 약 3건과 크리티컬 종료 오류 5건 이상을 수정했습니다.',metrics:['SQL 관련 문제 약 3건 개선','크리티컬 종료 오류 5건 이상 수정'],skill:{key:'csharp',value:4,label:'C# · WinForms',level:'중급'}},
    {id:'machat',group:'flutter',kind:'personal',date:'2024년 후반–2025년 후반',short:'MaChat',title:'MaChat',x:48,y:34,summary:'기획·설계·구현을 처음부터 끝까지 맡은 첫 개인 프로젝트입니다.',problem:'대량 채팅 기록을 매번 불러오면 읽기량과 대기 시간이 커지고, 같은 영단어를 반복 추론하면 AI API 호출이 늘어납니다.',solution:'채팅방당 최근 30개 메시지를 캐싱하고 나머지는 지연 로딩했습니다. Firestore에 마스터 Voca를 선처리해 반복 단어의 Gemini API 호출을 줄이도록 설계했습니다.',metrics:['채팅방별 캐시: 최근 30개','설계 비교 가정: 3개 방 × 방당 500개 메시지'],skill:{key:'flutter',value:6,label:'Flutter',level:'중상급'},link:'https://machat-f1450.web.app/',showModels:true,access:{id:'tester01@test.com',password:'Test1234!'},extra:'Firebase Firestore·Stream 실시간 채팅, Gemini API 기반 AI 채팅과 영단어 뜻·유의어·반의어 추론, 수퍼톤 API TTS를 구현했습니다.'},
    {id:'codeit',group:'codeit',kind:'official',date:'2026.03–현재',short:'코드잇 부트캠프',title:'코드잇 창업자 부트캠프',x:62,y:27,summary:'기능 중심 개발에서 시장을 읽고 검증하는 제품 개발로 관점을 전환했습니다.',problem:'MaChat을 만들며 기능을 완성하는 것만으로는 팔리는 제품이 되지 않는다고 느꼈습니다. 시장을 읽고 분석하며 고객의 수요를 판단하는 역량이 필요했습니다.',solution:'개발자 과정 대신 창업자 과정에 지원해 여러 시장 분석 기법과 MVP 구현 방법을 배우고, Sentinel부터 Vencubator까지 실험에 적용했습니다.',metrics:['수강: 2026.03–현재','종료 예정: 2026.10'],skill:null,status:'ongoing'},
    {id:'sentinel',group:'codeit',kind:'personal',date:'2026.03–2026.06',short:'Sentinel',title:'Sentinel',x:72,y:14,summary:'새벽 장애 대응 경험에서 출발한 인시던트 인사이트 서비스. 데모 인터뷰와 MVP로 수요를 검증한 뒤 중단했습니다.',problem:'PORTMIS 야간 장애 때 대응 방향을 찾지 못했던 경험에서, 인시던트 상황의 혼란을 줄여주는 서비스가 필요한지 궁금했습니다. 아이디어는 이전부터 있었지만 코드잇 과정에서 실행에 옮겼습니다.',solution:'2026년 3~6월 Reddit·OKKY 등에서 DevOps·SRE 전문가에게 데모를 보여주고 인터뷰했습니다. 채널에 따라 메시지 접근법을 달리해야 한다는 점을 배웠고, Rootly 창업자로부터 AI 시대에도 인시던트의 엔트로피를 낮추는 방법론에는 수요가 있을 것이라는 피드백을 받았습니다. MVP까지 개발했지만 시장 반응이 없어 중단했습니다.',metrics:['시장 검증: 2026.03–06 · Reddit·OKKY 등에서 전문가 인터뷰','데모 기반 검증 → MVP 개발 → 프로젝트 중단','시장 반응 없음; 품질·마케팅 접근성 부족은 본인의 회고'],skill:{key:'ai',value:2,label:'AI 코딩',level:'탐색'},link:'https://sentinel-demo-c12b7.web.app/'},
    {id:'hypora',group:'codeit',kind:'personal',date:'2026.06–2026.07',short:'Hypora',title:'Hypora',x:71,y:46,summary:'두루뭉술한 아이디어를 실행 가능한 구조로 바꾸는 코파일럿입니다.',problem:'저도 서비스를 만들 때 두루뭉술한 개념을 실행 가능한 형태로 구체화하는 과정이 번거로웠습니다. 같은 어려움을 겪는 사람을 페르소나로 가정하고 앱을 기획했습니다.',solution:'아이디어를 단계적으로 구조화하는 코파일럿을 만들고, 지인·카카오톡 오픈채팅방·네이버 블로그를 통해 배포해 반응을 확인했습니다.',metrics:['개발: 2026.06–07','검증 채널: 지인 · 카카오톡 오픈채팅방 · 네이버 블로그','결과: 지속 사용자는 확인되지 않음','피드백: 용어와 사용법이 어렵다'],insight:'이번 검증에서는 아이디어만 있는 불특정 다수의 사용자에게 낯선 용어와 복잡한 사용법이 진입 장벽이 됐습니다. 아이디어를 구조화하는 기능만으로는 지속적으로 사용할 이유를 만들지 못했습니다.',skill:{key:'ai',value:3,label:'AI 코딩',level:'발전'},link:'https://hypora-2026.vercel.app/'},
    {id:'persoracle',group:'codeit',kind:'personal',date:'2026.07–2026.08',short:'Persoracle',title:'Persoracle',x:83,y:28,summary:'AI 페르소나를 통해 아이디어를 검증하는 서비스. 가까운 지인에게 수요를 물었습니다.',problem:'Hypora에서는 아이디어를 정리하는 기능만으로 지속 사용을 만들지 못했습니다. AI 페르소나와의 대화가 아이디어 검증에 더 실질적인 가치를 줄 수 있는지 확인하고 싶었습니다.',solution:'AI 페르소나 기반 피드백 흐름을 설계하고, 비개발자·비창업자인 가까운 지인들에게 보여주며 반응을 들었습니다. 적극적인 외부 마케팅은 하지 않았습니다.',metrics:['개발·검증: 2026.07–08','검증 대상: 가까운 지인 (비개발자·비창업자)','피드백: 무엇을 하는 서비스인지 모르겠다 · 재미는 있지만 내게 필요하지 않다'],insight:'흥미로운 체험과 필요한 서비스는 다릅니다. 제한된 지인 검증에서 제품의 용도와 대상 고객이 충분히 명확하지 않다는 신호를 받았습니다.',skill:{key:'ai',value:4,label:'AI 코딩',level:'발전'},link:'https://persoracle-mvp-v1.vercel.app/'},
    {id:'pactfive',group:'codeit',kind:'personal',date:'2026.08–2026.09 초',short:'PactFive',title:'PactFive',x:83,y:64,summary:'5인 팀의 팀장으로 의뢰인·프리랜서 매칭 플랫폼을 22영업일 동안 개발했습니다.',problem:'여러 담당자가 AI를 활용해 동시에 개발할 때 코드 충돌을 막아야 했습니다. 반면 기능 사이의 상호작용 결정이 각 담당자에게서 팀장으로 충분히 전달되지 않아 통합이 어려웠습니다.',solution:'ERD·PRD를 기준으로 모노레포와 담당자별 독립 폴더 권한을 설계했습니다. 컨텍스트와 AGENTS.md로 워크플로우를 관리하고 매일 한 차례 통합해 코드·파일 충돌을 0건으로 유지했습니다. 로그인·세션 관리·프로젝트 CRUD·Toss Payments 샌드박스 결제·Google OAuth·에스크로를 구현했습니다.',metrics:['팀 규모: 5명','개발 기간: 22영업일 (2026.08–09 초)','코드·파일 충돌: 0건','구현: 로그인·세션·프로젝트 CRUD·샌드박스 결제·Google OAuth·에스크로'],insight:'독립적인 폴더만으로 협업이 완성되지는 않습니다. 기능 간 의사결정과 인터페이스 변경을 통합 과정에 남기는 절차가 필요했습니다.',skill:{key:'ai',value:5,label:'AI 코딩',level:'발전'},link:'https://pact-five-seven.vercel.app/'},
    {id:'vencubator',group:'codeit',kind:'personal',date:'2026.09 말–진행 중',short:'Vencubator',title:'Vencubator',x:94,y:47,summary:'Hypora와 Persoracle을 통합한 게임화 창업 코파일럿. 랜딩페이지·프로토타입을 배포해 반응을 확인 중입니다.',problem:'아이디어 구조화와 검증이 분리되면 흐름이 끊기고, 초기 창업 학습의 진입 마찰도 높아집니다.',solution:'Duolingo의 게임화에서 영감을 얻어 저마찰 UI/UX로 두 흐름을 통합했습니다. 9월 말 랜딩페이지와 프로토타입을 만들고 Threads·LinkedIn·오픈채팅방·SYDE·Disquiet에 홍보하며 시장 반응을 살피고 있습니다.',metrics:['배포: 2026년 9월 말 · 랜딩페이지 + 프로토타입','배포 3일 기준 누적 접속: 56명 (사용자 제공 수치)','홍보 채널: Threads · LinkedIn · 오픈채팅방 · SYDE · Disquiet'],skill:{key:'ai',value:6,label:'AI 코딩',level:'중상급'},link:'https://vencubator.vercel.app/',status:'ongoing'}
  ],
  relations: [
    {from:'qa',to:'potmis',kind:'work',title:'품질 확인 → 서비스 운영',insight:'홈페이지 QA에서 화면과 상호작용을 점검한 뒤, 같은 회사에서 실제 고객의 문의와 서비스 운영 문제를 다루는 업무로 범위가 넓어졌습니다. 직접적인 프로젝트 인과관계라기보다는 업무 이력의 연결입니다.'},
    {from:'potmis',to:'datacenter',kind:'work',title:'서비스 운영 → 인프라 점검',insight:'서비스를 모니터링하고 예외 상황에 대응하던 업무와, 그 서비스를 지탱하는 Linux 서버를 정기 점검한 업무가 같은 회사 이력에서 이어집니다. 특정 사건이 점검 업무를 촉발했다는 뜻은 아닙니다.'},
    {from:'datacenter',to:'winforms',kind:'work',title:'점검 → 직접 개선',insight:'현업 요구사항을 전달하던 역할에서 직접 분석하고 프로그램 오류를 수정하는 역할까지 확장됐습니다.'},
    {from:'sparta',to:'daily',kind:'flutter',title:'Flutter와 팀 프로젝트',insight:'팀 스파르타 창 5기에서 Flutter를 접했고, 그때 인연을 맺은 현업 초등 교사가 이끈 8인 팀에서 프론트엔드 기능을 구현했습니다.'},
    {from:'sparta',to:'machat',kind:'flutter',title:'Flutter와 첫 개인 프로젝트',insight:'Flutter를 익힌 뒤 MaChat에서 기획부터 설계·구현까지 직접 해보며 개인 제품 개발로 경험을 확장했습니다.'},
    {from:'machat',to:'codeit',kind:'bridge',title:'기능 구현 → 시장·고객 분석',insight:'MaChat을 A to Z로 만들며 기능 중심 개발만으로는 릴리즈할 수 없다는 깨달음을 얻었습니다. 시장 분석과 고객 분석이 필요하다고 느껴 코드잇 창업자 부트캠프로 이어졌습니다.'},
    {from:'potmis',to:'sentinel',kind:'catalyst',title:'새벽 장애 경험 → Sentinel',insight:'PORTMIS 야간 모니터링 중 새벽 3시경 일부 서비스가 다운됐을 때 대응 절차를 몰라 헤맸습니다. 그때의 혼란을 줄일 방법을 찾고 싶었던 기억이 이후 Sentinel 아이디어의 계기가 됐습니다.'},
    {from:'codeit',to:'sentinel',kind:'codeit',title:'AI와 MVP 실험',insight:'코드잇 부트캠프에서 Sentinel MVP를 바이브 코딩으로 설계하고 시장 검증을 시도했습니다.'},
    {from:'sentinel',to:'hypora',kind:'codeit',title:'바이브 코딩 → 구조화',insight:'Sentinel 이후 바이브 코딩에는 구조화된 개발 과정이 필요하다는 생각이 남았습니다. SDD를 도입하고 아이디어 자체의 구조화도 탐구했습니다.'},
    {from:'hypora',to:'persoracle',kind:'codeit',title:'구조화 → 수요 검증',insight:'Hypora를 지인·카카오톡 오픈채팅방·네이버 블로그에 배포했지만 지속 사용자는 확인되지 않았고, 용어와 사용법이 어렵다는 피드백을 받았습니다. 아이디어 구조화만으로는 수요를 만들기 어렵다는 판단이 AI 페르소나를 통한 아이디어 검증으로 이어졌습니다.'},
    {from:'persoracle',to:'pactfive',kind:'codeit',title:'개인 제품 검증 → 팀 협업',insight:'Persoracle은 개인 제품의 가치와 설명 방식을 검증했고, PactFive는 같은 부트캠프에서 5명이 함께 제품을 만드는 협업 실험이었습니다. 직접적인 문제·해결 관계가 아니라 과정상 다음 경험입니다.'},
    {from:'pactfive',to:'vencubator',kind:'codeit',title:'팀 협업의 회고 → 다음 제품',insight:'PactFive에서는 파일 충돌을 막았지만 기능 간 의사결정 전달이 부족했습니다. 이후 Vencubator에서는 제품 실험과 함께 개발·통합 과정을 더 명시적으로 다뤄야 한다는 질문을 가져갔습니다. 특정 방법을 적용했다는 검증된 결과는 아직 없습니다.'},
    {from:'hypora',to:'vencubator',kind:'integration',title:'아이디어 구조화의 통합',insight:'Hypora의 아이디어 구조화 흐름을 Vencubator의 한 축으로 통합하고 있습니다.'},
    {from:'persoracle',to:'vencubator',kind:'integration',title:'검증 흐름의 통합',insight:'Persoracle의 아이디어 검증 흐름을 Vencubator에 이어 붙여 창업 학습 경험을 구성하고 있습니다.'}
  ],
  skills:[{key:'flutter',label:'Flutter',color:'gold'},{key:'sql',label:'RDB · SQL',color:'blue'},{key:'linux',label:'Linux',color:'blue'},{key:'csharp',label:'C# · WinForms',color:'blue'},{key:'ai',label:'AI 코딩',color:'gold'}]
};
